### ISSUE TITLE
关于init()方法的疑问

### ISSUE THREAD

**Issue by qingtenglv** [jczh98/pica_python#1]
def init():
    ts = int(time.time())
    s = signature(init_url, ts, "GET")
    headers["signature"] = s
    headers["time"] = str(ts)
    return get(sign_url)
最后调用的是登录接口吗？

**Comment by qingtenglv** [comment]
反编译客户端发现调用的是https://139.59.113.68/init  okhttpclient初始化的时候做了https认证的操作  但是我用原来的这些代码去调用这个接口的时候总是timeout，何解？

**Comment by jczh98** [comment]
这个借口是用于获取pica三个路线的
最近pica后端改动了一些，具体情况我并不是特别清楚，sorry
